on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, reopened]

jobs:
    ubuntu20:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test

    ubuntu22:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test

    ubuntu22-download-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler --policy download install /usr/bin/
            - run: make test WSHANDLER=wshandler
            - run: sudo ./wshandler upgrade /usr/bin/
            - run: wshandler --version

    ubuntu22-snap-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler --policy snap install /usr/bin/
            - run: make test WSHANDLER=wshandler
            - run: sudo ./wshandler upgrade /usr/bin/
            - run: wshandler --version

    appimage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make appimage_deps
            - run: make appimage ARCH=x86_64 YQ_ARCH=amd64 WSHANDLER_VERSION=1.1.1
            - run: make appimage ARCH=aarch64 YQ_ARCH=arm64
            - run: make test WSHANDLER=./build/appimage/wshandler-x86_64.AppImage
            - run: sudo ./build/appimage/wshandler-x86_64.AppImage upgrade_appimage /usr/bin/
            - run: wshandler --version
