on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, reopened]

jobs:
    ubuntu20-download-yq:
        container: ubuntu:focal
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - run: apt update
            - run: apt upgrade -y
            - run: env DEBIAN_FRONTEND=noninteractive apt install --yes --no-install-recommends bash git sudo ca-certificates make
            - run: ./wshandler install_test_deps
            - run: ./wshandler -y yq --policy download install /usr/bin/
            - run: make test YAML_TOOL="auto"

    ubuntu22-gojq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler -y gojq --policy apt install /usr/bin/
            - run: make test YAML_TOOL="gojq"

    ubuntu22-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test YAML_TOOL="yq"

    ubuntu22-apt-gojq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler -y gojq --policy apt install /usr/bin/
            - run: make test WSHANDLER="wshandler -y gojq"
            - run: sudo ./wshandler upgrade /usr/bin/
            - run: wshandler --version

    ubuntu22-download-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler -y yq --policy download install /usr/bin/
            - run: make test WSHANDLER="wshandler -y yq"
            - run: sudo ./wshandler upgrade /usr/bin/
            - run: wshandler --version

    ubuntu22-snap-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler -y yq --policy snap install /usr/bin/
            - run: make test WSHANDLER="wshandler -y yq"
            - run: sudo ./wshandler upgrade /usr/bin/
            - run: wshandler --version

    ubuntu24-gojq:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler -y gojq --policy apt install /usr/bin/
            - run: make test YAML_TOOL="gojq"

    ubuntu24-yq:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test YAML_TOOL="yq"

    appimage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: make appimage_deps
            - run: make appimage ARCH=x86_64 YQ_ARCH=amd64 WSHANDLER_VERSION=1.1.1
            - run: make appimage ARCH=aarch64 YQ_ARCH=arm64
            - run: make test WSHANDLER=./build/appimage/wshandler-yq-x86_64.AppImage
            - run: sudo ./build/appimage/wshandler-yq-x86_64.AppImage upgrade_appimage /usr/bin/
            - run: wshandler --version
