on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, reopened]


env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    ubuntu20:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test

    ubuntu22:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: make test

    ubuntu22-download-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler --policy download install /usr/bin/
            - run: make test WSHANDLER=wshandler

    ubuntu22-snap-yq:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ./wshandler install_test_deps
            - run: sudo ./wshandler --policy snap install /usr/bin/
            - run: make test WSHANDLER=wshandler

    appimage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ${APT} desktop-file-utils
            - run: make appimage ARCH=x86_64 YQ_ARCH=amd64
            - run: make appimage ARCH=aarch64 YQ_ARCH=arm64
            - run: make test WSHANDLER=./build/appimage/wshandler-x86_64.AppImage
