on:
    push:
        tags:
            - '**'

env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    appimage:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
            - run: ${APT} desktop-file-utils
            - run: make appimage
            - run: make appimage ARCH=aarch64 YQ_ARCH=arm64
            - run: ./build/appimage/wshandler-x86_64.AppImage -r tests/update status
            - uses: softprops/action-gh-release@v1
              with:
                files: build/appimage/wshandler*.AppImage
                fail_on_unmatched_files: true
