on:
    push:
        tags:
            - '**'

env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    appimage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: ${APT} desktop-file-utils
            - run: make appimage ARCH=x86_64 YQ_ARCH=amd64
            - run: make appimage ARCH=aarch64 YQ_ARCH=arm64
            - run: ./build/appimage/wshandler-x86_64.AppImage -r tests/update status
            - uses: softprops/action-gh-release@v2
              with:
                files: |
                    build/appimage/wshandler*.AppImage
                    wshandler
                fail_on_unmatched_files: true
